import './globals.css'
import type { Metadata } from 'next'
import { Inter, Work_Sans } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

const work_sans = Work_Sans({
  subsets: ['latin'],
  weight: ['200', '300', '400', '500', '600', '700', '800', '900'],
});

export const metadata: Metadata = {
  title: 'Maiker Construction',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={work_sans.className}>
        {children}
      </body>
    </html>
  )
}
